/**
 * Story-time voiceover generator.
 *
 * Builds a narration line per story part (from the beats in brandFacts.ts) and
 * synthesises it to public/vo/story-<id>-p<n>.mp3, then writes the list of
 * generated ids into src/data/voiceovers.ts so the catalog wires the audio in.
 *
 * Providers (auto-detected from env, first one wins):
 *   ELEVENLABS_API_KEY  → ElevenLabs (set ELEVENLABS_VOICE_ID to pick a voice)
 *   OPENAI_API_KEY      → OpenAI tts-1 (set OPENAI_TTS_VOICE, default "onyx")
 *
 * No key? The script prints what to do and exits 0 without changing anything.
 * You can also bypass TTS entirely: drop your own recordings into public/vo/
 * named story-<id>-p<n>.mp3 and add their ids to src/data/voiceovers.ts.
 *
 * Usage:  npm run voiceover            # generate everything missing
 *         npm run voiceover -- --force # regenerate even if the mp3 exists
 */
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { STORIES } from '../src/data/brandFacts';
import { VOICEOVER_DIR } from '../src/data/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const voDir = path.join(root, 'public', VOICEOVER_DIR);
const force = process.argv.includes('--force');

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40);

/** One natural-sounding narration line per story part. */
const narrationFor = (beats: { text: string }[]) =>
  beats
    .map((b) => b.text.trim())
    .join(' ')
    .replace(/\s+/g, ' ');

type Job = { id: string; text: string };
const jobs: Job[] = [];
for (const story of STORIES) {
  story.parts.forEach((part, idx) => {
    jobs.push({ id: `story-${slug(story.id)}-p${idx + 1}`, text: narrationFor(part.beats) });
  });
}

async function synthOpenAI(text: string): Promise<Buffer> {
  const voice = process.env.OPENAI_TTS_VOICE || 'onyx';
  const res = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: 'tts-1', voice, input: text, response_format: 'mp3' }),
  });
  if (!res.ok) throw new Error(`OpenAI TTS ${res.status}: ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

async function synthElevenLabs(text: string): Promise<Buffer> {
  const voiceId = process.env.ELEVENLABS_VOICE_ID || '21m00Tcm4TlvDq8ikWAM'; // default "Rachel"
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: 'POST',
    headers: { 'xi-api-key': process.env.ELEVENLABS_API_KEY as string, 'Content-Type': 'application/json' },
    body: JSON.stringify({ text, model_id: 'eleven_multilingual_v2' }),
  });
  if (!res.ok) throw new Error(`ElevenLabs ${res.status}: ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

function pickProvider(): { name: string; synth: (t: string) => Promise<Buffer> } | null {
  if (process.env.ELEVENLABS_API_KEY) return { name: 'ElevenLabs', synth: synthElevenLabs };
  if (process.env.OPENAI_API_KEY) return { name: 'OpenAI tts-1', synth: synthOpenAI };
  return null;
}

function writeManifest(ids: string[]) {
  const file = path.join(root, 'src', 'data', 'voiceovers.ts');
  const body =
    `/**\n` +
    ` * IDs of story-time parts that have a narration file at\n` +
    ` * /public/${VOICEOVER_DIR}/<id>.mp3. AUTO-GENERATED by scripts/gen-voiceover.ts —\n` +
    ` * edit that script (or your reviews/stories) rather than this list by hand.\n` +
    ` */\n` +
    `export const VOICEOVER_IDS: string[] = ${JSON.stringify(ids.sort(), null, 2)};\n`;
  fs.writeFileSync(file, body);
}

async function main() {
  const provider = pickProvider();
  if (!provider) {
    console.log('No TTS provider configured. Set one of:');
    console.log('  ELEVENLABS_API_KEY (+ optional ELEVENLABS_VOICE_ID)');
    console.log('  OPENAI_API_KEY     (+ optional OPENAI_TTS_VOICE, default "onyx")');
    console.log('\nThen re-run:  npm run voiceover');
    console.log('\nOr supply your own recordings: drop story-<id>-p<n>.mp3 into');
    console.log(`  public/${VOICEOVER_DIR}/  and add the ids to src/data/voiceovers.ts`);
    console.log('\nNarration scripts (so you can record them):');
    for (const j of jobs) console.log(`\n[${j.id}]\n${j.text}`);
    return;
  }

  fs.mkdirSync(voDir, { recursive: true });
  console.log(`Generating ${jobs.length} narrations via ${provider.name}…`);
  const done: string[] = [];
  for (const j of jobs) {
    const out = path.join(voDir, `${j.id}.mp3`);
    if (fs.existsSync(out) && !force) {
      done.push(j.id);
      console.log(`  ✓ ${j.id} (exists, skipped)`);
      continue;
    }
    try {
      const buf = await provider.synth(j.text);
      fs.writeFileSync(out, buf);
      done.push(j.id);
      console.log(`  ✓ ${j.id}`);
    } catch (err) {
      console.error(`  ✗ ${j.id}: ${(err as Error).message}`);
    }
  }
  // Include any pre-existing recordings the user dropped in manually.
  const existing = fs
    .readdirSync(voDir)
    .filter((f) => f.endsWith('.mp3'))
    .map((f) => f.replace(/\.mp3$/, ''));
  const ids = Array.from(new Set([...done, ...existing]));
  writeManifest(ids);
  console.log(`\nWrote src/data/voiceovers.ts with ${ids.length} id(s). Re-render story-* to hear them.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
